DELETE FROM CATEGORIES;

DELETE FROM PRODUCTS;

DELETE FROM PRODUCTS_CATEGORIES;

DELETE FROM IMAGE_ASSETS;

DELETE FROM PRODUCTS_IMAGE_ASSETS;

INSERT INTO CATEGORIES (UID, PARENT_ID, NAME, DESCRIPTION, ICON, IMAGE_PATH)
SELECT *
FROM CSVREAD('src/main/resources/data/categories.csv');

INSERT INTO PRODUCTS (UID, NAME, SKU, REGULAR_PRICE, DISCOUNT_PRICE, DISCOUNT_PRICE_END_DATE, LOWEST_PRICE, DESCRIPTION,
                      SHORT_DESCRIPTION, NOTE, STATUS, PRODUCTSCOL, QUANTITY)
SELECT *
FROM CSVREAD('src/main/resources/data/products.csv');

INSERT INTO PRODUCTS_CATEGORIES (PRODUCTS_ID, CATEGORIES_ID)
SELECT *
FROM CSVREAD('src/main/resources/data/productscategories.csv');

INSERT INTO IMAGE_ASSETS (ASSET_URL)
SELECT *
FROM CSVREAD('src/main/resources/data/imageassets.csv');

INSERT INTO PRODUCTS_IMAGE_ASSETS (PRODUCT_ID, IMAGE_ASSETS_ID)
SELECT *
FROM CSVREAD('src/main/resources/data/productsimageassets.csv');
